In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np

import keras 
from keras.models import Sequential
from keras.layers import Conv1D, LSTM, Dense,Reshape,MaxPool1D

In [ ]:
time_series = np.array([0,1,3,2,5,1,4,6,9,5,4,5,2,1,5,7,2,1,8,4,4,7,5,3])

In [ ]:
time_series[0:2]

array([0, 1])

In [ ]:
def split_seq(seq,n):
  X,y = list(), list()
  for i in range (len(seq)):

    end_of_seq = n + i 
    if end_of_seq >len(seq)-1:
      break
    seq1 = seq[i:end_of_seq]
    seq2 = seq[end_of_seq]
# Add stuff to the list
    X.append(seq1)
    y.append(seq2)


  return np.array(X),np.array(y)
    

In [ ]:
split_seq(time_series,2)

(array([[0, 1],
        [1, 3],
        [3, 2],
        [2, 5],
        [5, 1],
        [1, 4],
        [4, 6],
        [6, 9],
        [9, 5],
        [5, 4],
        [4, 5],
        [5, 2],
        [2, 1],
        [1, 5],
        [5, 7],
        [7, 2],
        [2, 1],
        [1, 8],
        [8, 4],
        [4, 4],
        [4, 7],
        [7, 5]]),
 array([3, 2, 5, 1, 4, 6, 9, 5, 4, 5, 2, 1, 5, 7, 2, 1, 8, 4, 4, 7, 5, 3]))

In [ ]:
time_series.shape

(24,)

In [ ]:
X,y = split_seq(time_series, n=3)

In [ ]:
print(X.shape)
y.shape

(21, 3)


(21,)

In [ ]:
for i in range (len(X)):
  print(X[i],y[i])

[0 1 3] 2
[1 3 2] 5
[3 2 5] 1
[2 5 1] 4
[5 1 4] 6
[1 4 6] 9
[4 6 9] 5
[6 9 5] 4
[9 5 4] 5
[5 4 5] 2
[4 5 2] 1
[5 2 1] 5
[2 1 5] 7
[1 5 7] 2
[5 7 2] 1
[7 2 1] 8
[2 1 8] 4
[1 8 4] 4
[8 4 4] 7
[4 4 7] 5
[4 7 5] 3


In [ ]:
X.shape

(21, 3)

In [ ]:
X= X.reshape(21,3,1)

In [ ]:
X.shape

(21, 3, 1)

In [ ]:
# Adding an Additional dim to make compatible to NN

model = Sequential()
model.add(Conv1D(10,1 , activation='relu', input_shape = (23,1)))
model.add(Dense (1))
#model.add(Conv1D(filters=32, kernel_size=3, padding='same', activation='relu',input_dim = 3)))
#model.add(MaxPooling1D(4))
#model.add(LSTM(16))
#model.add(Dense(1))
model.compile(optimizer='adam', loss='mean_squared_error')

model.fit(X,y,epochs = 10000000)
#model.predict(X)
        # model.compile(optimizer='adam', loss='mean_squared_error', metrics=[metric])
        # model.compile(optimizer="sgd", loss="mse", metrics=[metric])
print(model.summary())

Streaming output truncated to the last 5000 lines.
Epoch 16113/10000000
1/1 [==============================] - 0s 1ms/step - loss: 4.9697
Epoch 16114/10000000
1/1 [==============================] - 0s 1ms/step - loss: 4.9697
Epoch 16115/10000000
1/1 [==============================] - 0s 1ms/step - loss: 4.9697
Epoch 16116/10000000
1/1 [==============================] - 0s 2ms/step - loss: 4.9697
Epoch 16117/10000000
1/1 [==============================] - 0s 2ms/step - loss: 4.9697
Epoch 16118/10000000
1/1 [==============================] - 0s 1ms/step - loss: 4.9697
Epoch 16119/10000000
1/1 [==============================] - 0s 2ms/step - loss: 4.9697
Epoch 16120/10000000
1/1 [==============================] - 0s 1ms/step - loss: 4.9697
Epoch 16121/10000000
1/1 [==============================] - 0s 1ms/step - loss: 4.9697
Epoch 16122/10000000
1/1 [==============================] - 0s 4ms/step - loss: 4.9697
Epoch 16123/10000000
1/1 [==============================] - 0s 1ms/step - loss:

KeyboardInterrupt: ignored